version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: fampay_assignment
    volumes:
      - .:/fampay_assignment
    ports:
      - "8000:8000"



      